name: container

on: push

jobs:
  
   node-docker:
      runs-on: ubuntu-latest
      services:
        app: 
          
          image: alialaa17/node-api
          
          ports: 
             - 3001:3000
          
        mongo:
          
           image: mongo
           ports: 
             - "2017:2017"
             
      steps:
           
         - name: multiline script 
           run: |
             node -v 
             npm -v
           
          
